// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('anu-vue')['AAlert']
    ABtn: typeof import('anu-vue')['ABtn']
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    AddBookButton: typeof import('./src/components/AddBookButton.vue')['default']
    AddBookForm: typeof import('./src/components/AddBookForm.vue')['default']
    ADialog: typeof import('anu-vue')['ADialog']
    ADrawer: typeof import('anu-vue')['ADrawer']
    ACheckbox: typeof import('anu-vue')['ACheckbox']
    AInput: typeof import('anu-vue')['AInput']
    ASelect: typeof import('anu-vue')['ASelect']
    ASwitch: typeof import('anu-vue')['ASwitch']
    BookDetails: typeof import('./src/components/BookDetails.vue')['default']
    CollectionList: typeof import('./src/components/CollectionList.vue')['default']
    DividerWithText: typeof import('./src/components/DividerWithText.vue')['default']
    EnterForm: typeof import('./src/components/EnterForm.vue')['default']
    FooterItem: typeof import('./src/components/FooterItem.vue')['default']
    ItemAvatar: typeof import('./src/components/ItemAvatar.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    MainDrawer: typeof import('./src/components/MainDrawer.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScannerUI: typeof import('./src/components/ScannerUI.vue')['default']
    SelectCollection: typeof import('./src/components/SelectCollection.vue')['default']
    TabItem: typeof import('./src/components/TabItem.vue')['default']
    TabsHeader: typeof import('./src/components/TabsHeader.vue')['default']
    ValidatedInput: typeof import('./src/components/ValidatedInput.vue')['default']
  }
}
