// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddBook: typeof import('./src/components/icons/AddBook.vue')['default']
    AddBookForm: typeof import('./src/components/AddBookForm.vue')['default']
    BarCodeIcon: typeof import('./src/components/icons/BarCodeIcon.vue')['default']
    BookIcon: typeof import('./src/components/icons/BookIcon.vue')['default']
    CollectionList: typeof import('./src/components/CollectionList.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    DividerWithText: typeof import('./src/components/DividerWithText.vue')['default']
    DotsVertical: typeof import('./src/components/icons/DotsVertical.vue')['default']
    EyeOffOutline: typeof import('./src/components/icons/EyeOffOutline.vue')['default']
    EyeOutline: typeof import('./src/components/icons/EyeOutline.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    PersonIcon: typeof import('./src/components/icons/PersonIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScannerUI: typeof import('./src/components/ScannerUI.vue')['default']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SpinnerIcon: typeof import('./src/components/icons/SpinnerIcon.vue')['default']
    TabItem: typeof import('./src/components/TabItem.vue')['default']
    TabsHeader: typeof import('./src/components/TabsHeader.vue')['default']
  }
}
